### ISSUE TITLE
The 'typed_ast' distribution was not found and is required by tlcpack.

### ISSUE THREAD

**Issue by renxida** [tlc-pack/tlcpack#42]
Hi! I'm using miniconda 4.10.0 to test out tlcpack.

attempting to run `tvmc` fails with the error in the title.

Please find what I did in the following terminal output.

I was using a conda env created for this purpose.

I am on CentOS 7.

```ShellSession

┌─[xr5ry@portal03]─[~]
└──╼ $cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


┌─[xr5ry@portal03]─[~]
└──╼ $tvmc --help
Traceback (most recent call last):
  File "/u/xr5ry/miniconda3/envs/tlcpack/bin/tvmc", line 33, in <module>
    sys.exit(load_entry_point('tlcpack==0.8.dev107+g7b11b9217', 'console_scripts', 'tvmc')())
  File "/u/xr5ry/miniconda3/envs/tlcpack/bin/tvmc", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/u/xr5ry/miniconda3/envs/tlcpack/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/u/xr5ry/miniconda3/envs/tlcpack/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/u/xr5ry/miniconda3/envs/tlcpack/lib/python3.8/site-packages/tvm/driver/tvmc/__init__.py", line 21, in <module>
    from . import autotuner
  File "/u/xr5ry/miniconda3/envs/tlcpack/lib/python3.8/site-packages/tvm/driver/tvmc/autotuner.py", line 34, in <module>
    from .main import register_parser
  File "/u/xr5ry/miniconda3/envs/tlcpack/lib/python3.8/site-packages/tvm/driver/tvmc/main.py", line 26, in <module>
    import pkg_resources
  File "/u/xr5ry/miniconda3/envs/tlcpack/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/u/xr5ry/miniconda3/envs/tlcpack/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/u/xr5ry/miniconda3/envs/tlcpack/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/u/xr5ry/miniconda3/envs/tlcpack/lib/python3.8/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/u/xr5ry/miniconda3/envs/tlcpack/lib/python3.8/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/u/xr5ry/miniconda3/envs/tlcpack/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'typed_ast' distribution was not found and is required by tlcpack
```

**Comment by renxida** [comment]
Update: I tried using "conda create --name mytlcpack -c tlcpack tlcpack-nightly" and it worked.

I believe using the nightly build solved it!
